### ISSUE TITLE
Null GetAtt version

### ISSUE THREAD

**Issue by revmischa** [daaru00/serverless-plugin-greengrass#2]
The CloudFormation template is invalid: `[/Resources/GreengrassFunctionDefinition/Type/InitialVersion/Functions/0/FunctionArn/Fn::Join/1/1/Fn::GetAtt/0]` 'null' values are not allowed in templates

```
          "Functions": [
            {
              "Id": "myapp-dev-monitor",
              "FunctionArn": {
                "Fn::Join": [
                  ":",
                  [
                    {
                      "Fn::GetAtt": [
                        "MonitorLambdaFunction",
                        "Arn"
                      ]
                    },
                    {
                      "Fn::GetAtt": [
                        null,
                        "Version"
                      ]
                    }
                  ]
                ]
              },
```
I get this on one machine and not on the other. Works on mac, fails on ubuntu. Weird.

**Comment by daaru00** [comment]
Hi @revmischa,

uhm, is a strange behaviour, I directly using an internal API of Serverless framework to retrieve function version identifier [functionObject.versionLogicalId](https://github.com/daaru00/serverless-plugin-greengrass/blob/6ba669ce4cdf3253849e6dd15671dd195e3809cb/hooks/beforePackageFinalize/index.js#L51), should not be empty.

> I get this on one machine and not on the other. Works on mac, fails on ubuntu. Weird.

Sorry but it is almost impossible that could be a problem related to OS, NodeJS is a cross-OS language, interpreted and not compiled (except some difference in access system resources and path), no difference between *nix OS, Unix (Mac) and Linux has quite the same NodeJS environment. I currently working (and I developed this plugin) using Linux Mint 19 (based on Ubuntu 18.04 LTS).

Please check that both source code are exactly the same (with same version of Serverless/plugins) and authentication (access key/secret key/profile..) is correctly set. Also try to deploy both project without this plugin and then re-add it later to avoid Serverless-related issues.

**Comment by revmischa** [comment]
Upgrading to latest serverless on the PC fixed it
